language: php
php:
  - 5.6
notifications:
  slack:
    secure: MsjjDAtCYveoIJRbGOJYHsSWUxBzstIBSBLg8euJDsteMqLZ7RymMfxfMHY/PeqGoNJaz7kd03EQIRERuO2mzEib9SawGMgYTSaekXCHWPqPnsc21fkMBsB6f9BZQbq82YSi1aFjW9OXMkMWIgnTRAkAjV63Vl/oE16keYHQLzoIiPB2G+8BflTysOdKKeQzXhy9Sr6DVBxEC+Faf810/X/Fmdc6tdyxaSdo9QcvD77Xl9kyERbbAFzeq4WDSKS0J/11Pbyma2nWK4IHYQCGSpKZFDy01eOWr9eDwZLzJ4L5dNz0Ml1mlqKZtce7X/cK6EFbS68Yzk3d6kaJqy6RPzWz2yPEYipO+L92cU9K/kHx4VmNLIxkno7DBW7P3iwLzuWUn7V7B5j182KnmLmlCt09WIzNQdtjvk3nmDtrcNFQ8jaqHQQRL2mV91KbqpTAczwcI93OCKJD/loAybSv8FZDkg8rzEuFUrLjvpLMToPljiGyP49BLRi5UxG2SYThRjgejJSU84OB1C016Rofrf63H12Hc/jvoMcH/z4ENJOMKtrpJwalbY2SoZKUfl71z5Q70CrFOWs+Us1DAxade16S9dCtW7Eir75wF47JW+XMA62TRfy9hv/pU9HJPmI9b+9HMl2Clw34bUCj5mPEwDlueA6fdiLHjswMXR5Pybg=
